---
- name: webhook-eda-demo
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Act on high CPU alerts
      condition: event.payload.alert == "cpu_high"
      action:
        run_job_template:
          name: "EDA Demo"        # Job template name in Controller
          organization: "Default"          # Controller org
          job_args:
            extra_vars:
              severity: "{{ event.payload.severity | default('unknown') }}"
              reason: "{{ event.payload.reason | default('n/a') }}"
              source_host: "{{ event.payload.host | default('unknown') }}"
#        run_playbook:
#          name: playbooks/respond.yml
#          extra_vars:
#            reason: "{{ event.payload.reason | default('n/a') }}"
#            source_host: "{{ event.payload.host | default('unknown') }}"
    - name: Log everything else
      condition: true
      action:
        print_event:
          pretty: true
